/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Excepciones.NegocioException;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tatzu
 */
public class frmSolicitarPlacas extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmSolicitarPlacas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombreFrame = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jLabelLicencia = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldPaterno = new javax.swing.JTextField();
        jLabelPaterno = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        datePickerNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelNacimiento = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelDatosPersonales = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabelTipo = new javax.swing.JLabel();
        jLabelCosto = new javax.swing.JLabel();
        jLabelFin = new javax.swing.JLabel();
        jLabelFechaFin = new javax.swing.JLabel();
        jLabelFechaInicio = new javax.swing.JLabel();
        jLabelExpiracion = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelMaterno = new javax.swing.JLabel();
        jTextFieldMaterno = new javax.swing.JTextField();
        jLabelRFC = new javax.swing.JLabel();
        jTextFieldRFC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelFondoMouseClicked(evt);
            }
        });
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelNombreFrame.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNombreFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreFrame.setText("Registro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabelNombreFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNombreFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButtonVolver.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVolver.setText("Volver");
        jButtonVolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 425, 134, 35));

        jButtonRegistrar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 425, 134, 35));

        jLabelLicencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelLicencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLicencia.setText("Licencia");
        jPanelFondo.add(jLabelLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 280, 20));

        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelFondo.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 127, -1));

        jLabelApellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelApellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelApellidos.setText("Apellidos");
        jPanelFondo.add(jLabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 94, 31));

        jTextFieldPaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelFondo.add(jTextFieldPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 127, -1));

        jLabelPaterno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPaterno.setText("Paterno:");
        jPanelFondo.add(jLabelPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 94, 31));

        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFecha.setText("Fecha de");
        jPanelFondo.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 94, 31));

        jTextFieldTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelFondo.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 127, -1));
        jPanelFondo.add(datePickerNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jLabelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTelefono.setText("Telefono:");
        jLabelTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanelFondo.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 94, 31));

        jLabelNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNacimiento.setText("Nacimiento");
        jPanelFondo.add(jLabelNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 31));

        jLabelCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantidad.setText("Cantidad");
        jPanelFondo.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 110, 31));

        jLabelDatosPersonales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDatosPersonales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDatosPersonales.setText("Datos Personales");
        jPanelFondo.add(jLabelDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 280, 20));

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre.setText("Nombre:");
        jPanelFondo.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 88, 31));

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 año", "2 años", "3 años", "5 años", "7 años", "10 años" }));
        jComboBoxTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBoxTipoMouseExited(evt);
            }
        });
        jPanelFondo.add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 110, -1));

        jLabelTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipo.setText("Tipo: ");
        jPanelFondo.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 88, 31));

        jLabelCosto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCosto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCosto.setText("Costo:");
        jPanelFondo.add(jLabelCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 88, 31));

        jLabelFin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFin.setText("Fin");
        jPanelFondo.add(jLabelFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 88, 31));

        jLabelFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFechaFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFechaFin.setText("FechaFin");
        jPanelFondo.add(jLabelFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 310, 31));

        jLabelFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFechaInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFechaInicio.setText("FechaInicio");
        jPanelFondo.add(jLabelFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 310, 31));

        jLabelExpiracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelExpiracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExpiracion.setText("Expiracion");
        jPanelFondo.add(jLabelExpiracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 88, 31));

        jLabelInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInicio.setText("Inicio");
        jPanelFondo.add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 88, 31));

        jLabelMaterno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelMaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMaterno.setText("Materno:");
        jPanelFondo.add(jLabelMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 94, 31));

        jTextFieldMaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelFondo.add(jTextFieldMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 127, -1));

        jLabelRFC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelRFC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRFC.setText("RFC:");
        jPanelFondo.add(jLabelRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 88, 31));

        jTextFieldRFC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelFondo.add(jTextFieldRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 127, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        ControlGUI.getInstancia().mostrarMenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        try {
            ControlGUI.getInstancia().registrarPersona(
                    this.jTextFieldRFC.getText(),
                    this.jTextFieldNombre.getText(),
                    this.jTextFieldPaterno.getText(),
                    this.jTextFieldMaterno.getText(),
                    this.jTextFieldTelefono.getText(),
                    Date.from(this.datePickerNacimiento.getDate().atStartOfDay(ZoneId.systemDefault()).toInstant()),
                    this.jComboBoxTipo.getItemAt(this.jComboBoxTipo.getSelectedIndex())
            );
            ControlGUI.getInstancia().mostrarMenuPrincipal();
            this.dispose();
        } catch (NegocioException ex) {
            Logger.getLogger(frmSolicitarPlacas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jPanelFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFondoMouseClicked
      
        
    }//GEN-LAST:event_jPanelFondoMouseClicked

    private void jComboBoxTipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoMouseExited
        this.actualizar();
    }//GEN-LAST:event_jComboBoxTipoMouseExited
    public void actualizar(){
         Date fechaInicio = new Date(); // fecha actual
        Date fechaFin;
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fechaInicio);
        String tipo = this.jComboBoxTipo.getItemAt(this.jComboBoxTipo.getSelectedIndex());
        if (tipo.equalsIgnoreCase("1 año")) {
            this.jLabelCantidad.setText("500.0");
            this.jLabelFechaInicio.setText(calendar.getTime().toString());
            calendar.add(Calendar.YEAR, 1); // suma 1 años
            fechaFin = calendar.getTime();
            this.jLabelFechaFin.setText(calendar.getTime().toString());
        } else if (tipo.equalsIgnoreCase("2 años")) {
            this.jLabelCantidad.setText("900.0");
            this.jLabelFechaInicio.setText(calendar.getTime().toString());
            calendar.add(Calendar.YEAR, 2); // suma 2 años
            fechaFin = calendar.getTime();
            this.jLabelFechaFin.setText(calendar.getTime().toString());
        } else {
            this.jLabelCantidad.setText("1200.0");
            this.jLabelFechaInicio.setText(calendar.getTime().toString());
            int años = Integer.parseInt(tipo.split(" ")[0]);
            calendar.add(Calendar.YEAR, años); // suma 3 años o mas
            fechaFin = calendar.getTime();
            this.jLabelFechaFin.setText(calendar.getTime().toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePickerNacimiento;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCosto;
    private javax.swing.JLabel jLabelDatosPersonales;
    private javax.swing.JLabel jLabelExpiracion;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFechaFin;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelFin;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLicencia;
    private javax.swing.JLabel jLabelMaterno;
    private javax.swing.JLabel jLabelNacimiento;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreFrame;
    private javax.swing.JLabel jLabelPaterno;
    private javax.swing.JLabel jLabelRFC;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JTextField jTextFieldMaterno;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPaterno;
    private javax.swing.JTextField jTextFieldRFC;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
