/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Excepciones.NegocioException;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tatzu
 */
public class frmSolicitarPlacas extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmSolicitarPlacas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombreFrame = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jButtonSolicitar = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldPaterno = new javax.swing.JTextField();
        jLabelLinea = new javax.swing.JLabel();
        jTextFieldRFCDueño = new javax.swing.JTextField();
        jLabelModelo = new javax.swing.JLabel();
        jLabelRFCDueño = new javax.swing.JLabel();
        jLabelDatosPersonales = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jTextFieldMaterno = new javax.swing.JTextField();
        jLabelNumeroSerie = new javax.swing.JLabel();
        jTextFieldNumeroSerie = new javax.swing.JTextField();
        jTextFieldTelefono1 = new javax.swing.JTextField();
        jButtonVerificarDueno = new javax.swing.JButton();
        jLabelDueno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelFondoMouseClicked(evt);
            }
        });
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelNombreFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreFrame.setText("Solicitar Placas");
        jLabelNombreFrame.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabelNombreFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNombreFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButtonVolver.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVolver.setText("Volver");
        jButtonVolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 425, 134, 35));

        jButtonSolicitar.setText("Solicitar");
        jButtonSolicitar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSolicitar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitarActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 425, 134, 35));

        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelFondo.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 127, -1));

        jTextFieldPaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelFondo.add(jTextFieldPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 127, -1));

        jLabelLinea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLinea.setText("Linea:");
        jLabelLinea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanelFondo.add(jLabelLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, 31));

        jTextFieldRFCDueño.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelFondo.add(jTextFieldRFCDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 127, -1));

        jLabelModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModelo.setText("Modelo:");
        jLabelModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanelFondo.add(jLabelModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 94, 31));

        jLabelRFCDueño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRFCDueño.setText("RFC Dueño:");
        jLabelRFCDueño.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanelFondo.add(jLabelRFCDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 31));

        jLabelDatosPersonales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDatosPersonales.setText("Datos Del Automovil");
        jLabelDatosPersonales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanelFondo.add(jLabelDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 280, 20));

        jLabelMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMarca.setText("Marca: ");
        jLabelMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanelFondo.add(jLabelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, 31));

        jLabelColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelColor.setText("Color:");
        jLabelColor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanelFondo.add(jLabelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 94, 31));

        jTextFieldMaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelFondo.add(jTextFieldMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 127, -1));

        jLabelNumeroSerie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumeroSerie.setText("Numero de Serie:");
        jLabelNumeroSerie.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanelFondo.add(jLabelNumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 150, 31));

        jTextFieldNumeroSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelFondo.add(jTextFieldNumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 127, -1));

        jTextFieldTelefono1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelFondo.add(jTextFieldTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 127, -1));

        jButtonVerificarDueno.setText("Verificar Dueño");
        jPanelFondo.add(jButtonVerificarDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 130, -1));

        jLabelDueno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDueno.setText("Dueño");
        jPanelFondo.add(jLabelDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        ControlGUI.getInstancia().mostrarMenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitarActionPerformed
     
    }//GEN-LAST:event_jButtonSolicitarActionPerformed

    private void jPanelFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFondoMouseClicked
      
        
    }//GEN-LAST:event_jPanelFondoMouseClicked
    public void actualizar(){
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSolicitar;
    private javax.swing.JButton jButtonVerificarDueno;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelDatosPersonales;
    private javax.swing.JLabel jLabelDueno;
    private javax.swing.JLabel jLabelLinea;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelNombreFrame;
    private javax.swing.JLabel jLabelNumeroSerie;
    private javax.swing.JLabel jLabelRFCDueño;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JTextField jTextFieldMaterno;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroSerie;
    private javax.swing.JTextField jTextFieldPaterno;
    private javax.swing.JTextField jTextFieldRFCDueño;
    private javax.swing.JTextField jTextFieldTelefono1;
    // End of variables declaration//GEN-END:variables
}
